CHUNK_SIZE = 4000
TRANSCRIPT_MAX_CHARS = 5000

OLLAMA_BASE_URL = "http://localhost:11434"
OLLAMA_GENERATE_URL = f"{OLLAMA_BASE_URL}/api/generate"
OLLAMA_TAGS_URL = f"{OLLAMA_BASE_URL}/api/tags"
OLLAMA_MODEL = "qwen3:1.7b"
OLLAMA_TIMEOUT = 120

CLASSIFY_INTERVAL = 5.0
VOSK_MODEL_PATH = "models/vosk-model"
GPIO_PIN = 18
